name: Semantic Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Verify the integrity of provenance attestations and registry signatures
        run: pnpm audit signatures
      
      - name: Build
        run: pnpm build
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GAT_SHADCN_AI_TOKEN }}
        run: npx semantic-release